### ISSUE TITLE
Apply new green logo to MediaWiki www.open-bio.org

### ISSUE THREAD

**Issue by peterjc** [OBF/Plumbing#1]
See https://github.com/OBF/obf-docs/issues/43

I'm not sure immediately how to do this, not obvious if via https://www.open-bio.org/wiki/Special:SpecialPages

**Comment by peterjc** [comment]
@cjfields pointed out https://www.mediawiki.org/wiki/Manual:$wgLogo

**Comment by hlapp** [comment]
Done. Used 144x144 and outside-transparent version of the circle logo.

**Comment by peterjc** [comment]
That looks very nice 👍
