### ISSUE TITLE
Apply new green logo to WordPress news.open-bio.org

### ISSUE THREAD

**Issue by peterjc** [OBF/Plumbing#2]
See https://github.com/OBF/obf-docs/issues/43

**Comment by cjfields** [comment]
The site icon was changed to the symbol on the right and the header for the main page is the full symbol (possibly a bit overpowering?).  [It's live now](https://news.open-bio.org).  

It's pretty simple to modify: https://en.support.wordpress.com/site-logo/

**Comment by peterjc** [comment]
I think we might want to review the theme to go better with this image, but excellent - thank you.

**Comment by hlapp** [comment]
Isn't there still the O|B|F logo at the top left? (And I thought that's where the logo would go.)

**Comment by peterjc** [comment]
Well spotted.

That was just text, "O|B|F News", fixed now to read "OBF News"
